### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by zakiryanova-java** [zakiryanova-java/Sportmaster#1]
@coursar , прошу проверить ДЗ: Homework1, Homework2. Спасибо.

**Comment by coursar** [comment]
Пофиксить #2, #3. #4 - учесть при сдаче следующих ДЗ.

**Comment by zakiryanova-java** [comment]
@coursar, проверить Homework1 (расход топлива и калькулятор обоев в одном репозитории).
Не занесены в таблицу домашек.
