### ISSUE TITLE
Репозитории нужно называть как проекты, например, sportmaster

### ISSUE THREAD

**Issue by coursar** [zakiryanova-java/Sportmaster#4]

**Comment by coursar** [comment]
Не закрывайте issue коммитами, которые не имеют отношение к issue

**Comment by zakiryanova-java** [comment]
@coursar, Есть ли возможность переименовать репозиторий в GH? В Идее переименовано с помощью Shift+F6 и классы, и наименование модуля.

**Comment by coursar** [comment]
В настройках -> Settings
